### ISSUE TITLE
Mappe Spieler auf Client / Multi Client Spiel

### ISSUE THREAD

**Issue by fredo** [janKir/wizard-online#7]
Als client möchte ich über den Browser als Spieler am Spiel teilnehmen. Ich sehe als Client nur meine Spielfigur und meine Karten.

Jeder weitere Client ist ein weiterer Spieler im Spiel und hat seinen eigenen View (eigene Karten)

**Comment by janKir** [comment]
wurde durch #20 teilweise umgesetzt. Allerdings finden sich alle Spieler Clients noch im selben Browser Fenster.

**Comment by janKir** [comment]
closed by #34
